name: Dictyexpress-js build

on:
  push:
    branches:
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  NODE_VERSION: 20
  S3_BUCKET: genialis-share-ci-artifact-eu-west-1
  S3_BUCKET_PREFIX: dictyexpress-js

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Generate environment variables
        run: |
          # All triggers.
          SHORT_SHA=$(git rev-parse --short HEAD)
          VERSION="dev-${SHORT_SHA}"

          # Override VERSION in tagged commits.
          if ${{ github.ref_type == 'tag' }};
          # Do not wrap conditions in brackets or quotes here, since bash would evaluate it as a string.
          then
            VERSION=${{ github.ref_name }}
          fi

          # Set environment for later steps.
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "FILENAME=dictyexpress-js-$VERSION.tar.gz" >> $GITHUB_ENV
      - name: Install NPM packages
        run: yarn
      - name: Build bundle
        env:
          VITE_APP_DEPLOY_ENV: "staging"
          VITE_APP_COMMIT_SHA: ${{ github.sha }}
        run: yarn build
      - name: Compress the build folder
        run: tar -czf ${{ env.FILENAME }} ./build/
      - name: Copy the bundle to the S3 bucket
        run: |
          aws s3 cp ${{ env.FILENAME }} s3://${{ env.S3_BUCKET }}/${{ env.S3_BUCKET_PREFIX }}/${{ env.FILENAME }}
